services:

  alive-webapp:
    build:
      context: ./websocket-alive/express
      dockerfile: Dockerfile
    container_name: alive-webapp
    environment:
      - NODE_ENV=production
      - MODE=server
      - DB_HOST=alive-db
      - DB_PORT=5432
      - DB_NAME=gestmed_alive_db
      - DB_USER=gestmed_user
      - DB_PASSWORD=gestmed_password
      - PORT=3000
    ports:
      - "3005:3000"
    depends_on:
      alive-db:
        condition: service_healthy
    networks:
      - gestmed-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
